#!/usr/bin/env node
/**
 * Count the lines in this project, and say honestly who wrote them.
 *
 * This is the only allowed answer to "how big is it". Nobody hand-counts with a shell
 * one-liner, because a hand count is a number nobody can reproduce and everybody
 * rounds in their own favour.
 *
 * The authorship split uses `git blame` over SURVIVING lines, not added-line churn.
 * Churn flatters whoever wrote the most drafts; surviving lines describe what is
 * actually in the repository today, which is the only thing a reader can check.
 */

import { execFileSync } from 'node:child_process';
import { readFileSync, statSync } from 'node:fs';
import { join, resolve, extname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(fileURLToPath(new URL('..', import.meta.url)));

/** Stated exclusions, so the total means something. */
const EXCLUDED_PATTERNS = [
  /^node_modules\//,
  /^release\//,
  /^dist\//,
  /(^|\/)package-lock\.json$/,
  /(^|\/)tools\/wiki-cache\//,
];

/** Generated by a committed script, so counted separately from hand-written work. */
const GENERATED_PATTERNS = [
  /^src\/data\/(towers|enemies)\//,
  /^site\/docs-bundle\.json$/,
  /^build\/icon\./,
  /^social-preview\.png$/,
];

const CATEGORIES = [
  { name: 'simulation', test: (p) => p.startsWith('src/sim/') },
  { name: 'data', test: (p) => p.startsWith('src/data/') },
  { name: 'interface', test: (p) => p.startsWith('src/render/') || p.startsWith('src/ui/') },
  { name: 'desktop shell', test: (p) => p.startsWith('electron/') },
  { name: 'site', test: (p) => p.startsWith('site/') },
  { name: 'tests', test: (p) => p.startsWith('tests/') },
  { name: 'tooling', test: (p) => p.startsWith('tools/') || p.startsWith('scripts/') },
  { name: 'documentation', test: (p) => p.startsWith('docs/') || extname(p) === '.md' },
  { name: 'other', test: () => true },
];

/** Agent identities, so the split is by who actually authored rather than by guess. */
const AGENT_AUTHORS = [/^Claude/i];

function tracked() {
  return execFileSync('git', ['ls-files'], { cwd: ROOT, encoding: 'utf8' })
    .split('\n')
    .map((line) => line.trim())
    .filter(Boolean)
    .filter((path) => !EXCLUDED_PATTERNS.some((pattern) => pattern.test(path)));
}

/**
 * @param {string} path
 * @returns {boolean}
 */
function isTextFile(path) {
  const binary = ['.png', '.jpg', '.jpeg', '.webp', '.ico', '.gif', '.zip', '.7z', '.woff2'];
  return !binary.includes(extname(path).toLowerCase());
}

const files = tracked();
const rows = new Map(CATEGORIES.map((c) => [c.name, { files: 0, total: 0, nonBlank: 0, generated: 0 }]));

let grandTotal = 0;
let grandNonBlank = 0;
let generatedTotal = 0;

for (const path of files) {
  const full = join(ROOT, path);
  let lines = 0;
  let nonBlank = 0;
  if (isTextFile(path)) {
    // CRLF aware. Splitting on a bare newline and forgetting the carriage return is
    // how a derived list quietly comes out empty elsewhere in this project.
    const text = readFileSync(full, 'utf8').split(/\r\n|\n|\r/);
    lines = text.length;
    nonBlank = text.filter((line) => line.trim().length > 0).length;
  } else {
    lines = 0;
    nonBlank = 0;
  }

  const generated = GENERATED_PATTERNS.some((pattern) => pattern.test(path));
  const category = CATEGORIES.find((c) => c.test(path));
  const row = rows.get(category.name);
  row.files += 1;
  row.total += lines;
  row.nonBlank += nonBlank;
  if (generated) row.generated += lines;

  grandTotal += lines;
  grandNonBlank += nonBlank;
  if (generated) generatedTotal += lines;
}

/** Surviving-line authorship, via blame. */
let agentLines = 0;
let personLines = 0;
let blameFailures = 0;

for (const path of files) {
  if (!isTextFile(path)) continue;
  try {
    const blame = execFileSync('git', ['blame', '--line-porcelain', '--', path], {
      cwd: ROOT,
      encoding: 'utf8',
      maxBuffer: 64 * 1024 * 1024,
    });
    for (const line of blame.split('\n')) {
      if (!line.startsWith('author ')) continue;
      const author = line.slice('author '.length).trim();
      if (AGENT_AUTHORS.some((pattern) => pattern.test(author))) agentLines += 1;
      else personLines += 1;
    }
  } catch {
    blameFailures += 1;
  }
}

const pad = (value, width) => String(value).padStart(width);
const lines = [];
lines.push('| Area | Files | Lines | Non-blank | Generated |');
lines.push('| --- | ---: | ---: | ---: | ---: |');
for (const category of CATEGORIES) {
  const row = rows.get(category.name);
  if (row.files === 0) continue;
  lines.push(
    '| ' + category.name + ' | ' + row.files + ' | ' + row.total + ' | ' + row.nonBlank +
      ' | ' + row.generated + ' |',
  );
}
lines.push('| **total** | **' + files.length + '** | **' + grandTotal + '** | **' + grandNonBlank + '** | **' + generatedTotal + '** |');
lines.push('');
lines.push('Excluded from the counts above: dependencies, packaged output, the lockfile and');
lines.push('the scraped statistics cache. Generated lines are produced by a committed script');
lines.push('and are counted separately from hand-written work.');
lines.push('');

const authored = agentLines + personLines;
if (authored > 0) {
  const agentShare = ((agentLines / authored) * 100).toFixed(1);
  lines.push('Surviving lines by author, measured with `git blame` over what is actually in the');
  lines.push('repository rather than over added-line churn:');
  lines.push('');
  lines.push('| Author | Surviving lines | Share |');
  lines.push('| --- | ---: | ---: |');
  lines.push('| agent | ' + agentLines + ' | ' + agentShare + '% |');
  lines.push('| person | ' + personLines + ' | ' + (100 - Number(agentShare)).toFixed(1) + '% |');
  if (blameFailures > 0) {
    lines.push('');
    lines.push(blameFailures + ' file(s) could not be attributed and are excluded from the split.');
  }
}

const report = lines.join('\n');
const outputPath = process.argv[2];
if (outputPath) {
  const { writeFileSync } = await import('node:fs');
  writeFileSync(outputPath, report + '\n');
  console.log('wrote line count report to ' + outputPath);
}
console.log(report);
